language: python
arch:
  - arm64
  - amd64
  
cache:
  directories:
  - $HOME/nats-server

python:
  - "3.8" 

before_install:
  - bash ./script/install_nats.sh

before_script:
  - export PATH=$HOME/nats-server:$PATH

install:
  - pip install -e .[nkeys]

script:
  - make ci
  
notifications:
  email: false

sudo: true
dist: xenial

